import AppKit
import Foundation

/// A single clipboard history entry (ported verbatim from tama-agent).
struct ClipboardEntry: Codable, Identifiable {
    let id: UUID
    let timestamp: Date
    let contentType: ContentType
    let textContent: String?
    let imageData: Data?
    let fileURL: String?
    let sourceAppName: String?
    let sourceAppBundle: String?

    enum ContentType: String, Codable {
        case text
        case image
        case fileURL
    }

    /// Truncated preview for the list. Matches the 50-character title limit.
    var preview: String {
        switch contentType {
        case .text:
            guard let text = textContent else { return "" }
            let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
                .replacingOccurrences(of: "\n", with: " ")
            guard trimmed.count > 50 else { return trimmed }
            let prefix = String(trimmed.prefix(50))
            if let lastSpace = prefix.lastIndex(of: " ") {
                return String(prefix[..<lastSpace]) + "…"
            }
            return prefix + "…"
        case .image:
            return "[Image]"
        case .fileURL:
            guard let path = fileURL else { return "[File]" }
            return (path as NSString).lastPathComponent
        }
    }

    var copyableText: String? {
        switch contentType {
        case .text: return textContent
        case .fileURL: return fileURL
        case .image: return nil
        }
    }
}

/// Persists clipboard history entries to disk (25-entry ring, deduplicated).
@MainActor
final class ClipboardStore: ObservableObject {
    static let shared = ClipboardStore()

    @Published private(set) var entries: [ClipboardEntry] = []
    private let maxEntries = 25

    private let storageURL: URL = {
        let base = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask)[0]
        let dir = base.appendingPathComponent("Universe", isDirectory: true)
        try? FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        return dir.appendingPathComponent("clipboard-history.json")
    }()

    private init() { load() }

    func add(_ entry: ClipboardEntry) {
        // Deduplicate: skip if any existing entry has identical content.
        let isDuplicate = entries.contains { existing in
            guard existing.contentType == entry.contentType else { return false }
            switch entry.contentType {
            case .text: return existing.textContent == entry.textContent
            case .fileURL: return existing.fileURL == entry.fileURL
            case .image: return existing.imageData == entry.imageData
            }
        }
        if isDuplicate { return }

        entries.insert(entry, at: 0)
        if entries.count > maxEntries {
            entries = Array(entries.prefix(maxEntries))
        }
        save()
    }

    func search(query: String) -> [ClipboardEntry] {
        guard !query.isEmpty else { return entries }
        let lowered = query.lowercased()
        return entries.filter { $0.preview.lowercased().contains(lowered) }
    }

    func delete(_ entry: ClipboardEntry) {
        entries.removeAll { $0.id == entry.id }
        save()
    }

    private func save() {
        guard let data = try? JSONEncoder().encode(entries) else { return }
        try? data.write(to: storageURL, options: .atomic)
    }

    private func load() {
        guard let data = try? Data(contentsOf: storageURL),
              let decoded = try? JSONDecoder().decode([ClipboardEntry].self, from: data) else { return }
        entries = decoded
    }
}

/// Polls NSPasteboard for changes and records new entries (ported from tama-agent).
@MainActor
final class ClipboardMonitor {
    static let shared = ClipboardMonitor()

    private var timer: Timer?
    private var lastChangeCount: Int

    /// Set briefly when we ourselves write to the pasteboard so we don't
    /// capture our own paste-back operations.
    var skipNextChange = false

    /// Pasteboard types that indicate sensitive or ephemeral content
    /// (password managers, text expanders). See http://nspasteboard.org.
    private let ignoredTypes: Set<NSPasteboard.PasteboardType> = [
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
        NSPasteboard.PasteboardType("com.agilebits.onepassword"),
        NSPasteboard.PasteboardType("de.petermaurer.TransientPasteboardType"),
        NSPasteboard.PasteboardType("com.typeit4me.clipping"),
    ]

    private init() {
        lastChangeCount = NSPasteboard.general.changeCount
    }

    func start() {
        guard timer == nil else { return }
        timer = Timer.scheduledTimer(withTimeInterval: 0.5, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated { self?.checkPasteboard() }
        }
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    private func checkPasteboard() {
        let pb = NSPasteboard.general
        guard pb.changeCount != lastChangeCount else { return }
        lastChangeCount = pb.changeCount

        if skipNextChange {
            skipNextChange = false
            return
        }

        // Skip concealed/transient content (passwords, text expanders, etc.)
        let types = Set(pb.types ?? [])
        if !types.isDisjoint(with: ignoredTypes) { return }

        let sourceApp = NSWorkspace.shared.frontmostApplication
        let appName = sourceApp?.localizedName
        let appBundle = sourceApp?.bundleIdentifier

        if let text = pb.string(forType: .string), !text.isEmpty {
            ClipboardStore.shared.add(ClipboardEntry(
                id: UUID(), timestamp: Date(), contentType: .text,
                textContent: text, imageData: nil, fileURL: nil,
                sourceAppName: appName, sourceAppBundle: appBundle
            ))
            return
        }

        if let urls = pb.readObjects(forClasses: [NSURL.self]) as? [URL],
           let url = urls.first {
            ClipboardStore.shared.add(ClipboardEntry(
                id: UUID(), timestamp: Date(), contentType: .fileURL,
                textContent: nil, imageData: nil, fileURL: url.path,
                sourceAppName: appName, sourceAppBundle: appBundle
            ))
            return
        }

        if let tiffData = pb.data(forType: .tiff),
           let image = NSImage(data: tiffData),
           let pngData = image.tiffRepresentation.flatMap({
               NSBitmapImageRep(data: $0)?.representation(using: .png, properties: [:])
           }) {
            // Only store images up to 500KB to avoid bloating the store.
            guard pngData.count <= 500_000 else { return }
            ClipboardStore.shared.add(ClipboardEntry(
                id: UUID(), timestamp: Date(), contentType: .image,
                textContent: nil, imageData: pngData, fileURL: nil,
                sourceAppName: appName, sourceAppBundle: appBundle
            ))
        }
    }
}
